### ISSUE TITLE
unicode(v) doesn't work on python 3+

### ISSUE THREAD

**Issue by scuerda** [ckan/ckanapi#100]
When iterating over `data_dict` if there is a file to upload, there is a call to `unicode` that breaks on Python 3.

```python
            if isinstance(v, (int, float)):
                v = unicode(v)
            data_dict[k.encode('utf-8')] = v.encode('utf-8')
```
https://github.com/ckan/ckanapi/blob/master/ckanapi/common.py#L80-L82

adding

`from builtins import str as text` 

and changing to 

```python
            if isinstance(v, (int, float)):
                v = text(v)
            data_dict[k.encode('utf-8')] = v.encode('utf-8')
```

Seems to resolve the issue. PR forthcoming.

**Comment by wardi** [comment]
Thanks!
