### ISSUE TITLE
 Problem when I install in Python 3

### ISSUE THREAD

**Issue by Artimael** [ckan/ckanapi#110]
Hi, I ave a problem when I install the api in Python 3

![captura](https://cloud.githubusercontent.com/assets/9206105/22074605/a9564a5e-dd87-11e6-8a81-3215bed96be2.PNG)
 
I attach a image

**Comment by TkTech** [comment]
CKAN does not support Python 3.

**Comment by wardi** [comment]
Yes, try again without ckan installed in your environment and you can use ckanapi's RemoteCKAN class (only). ckanapi tries to import ckan so you can run LocalCKAN calls but that only works with Python 2 right now.
