### ISSUE TITLE
Suggestion: provide ability to specify custom requests session

### ISSUE THREAD

**Issue by Toshakins** [ckan/ckanapi#121]
In custom scenarios, it could be helpful to have additional control over HTTP transport(i.e. `requests` library). Example: retry with exponential back-off or switching off SSL verification in local environments.

I propose to add a new parameter(`session`) to the `RemoteCKAN`'s constructor.

Moreover, if that's a case, I would like to help with the implementation :)

Do maintainers consider this proposal useful?

**Comment by mcarans** [comment]
I am not a maintainer but I consider this extremely useful. In fact I was just about to open a ticket for retry logic!

**Comment by mcarans** [comment]
@wardi @davidread What do you think?

**Comment by mcarans** [comment]
@Toshakins I suggest making a pull request and then we can ask for it to be reviewed.

**Comment by mcarans** [comment]
I have made a pull request: https://github.com/ckan/ckanapi/pull/122

**Comment by Toshakins** [comment]
Closing this issue as PR got merged. The detachable session is available in the `master` branch. The change will be available through Pypy after the next release.
