### ISSUE TITLE
List of actions = 404

### ISSUE THREAD

**Issue by Br3nda** [ckan/ckanapi#126]
I'm looking for a list of actions.
the Readme has a link to http://docs.ckan.org/en/latest/api.html
![image](https://user-images.githubusercontent.com/12266/31522565-f2fe5916-b00a-11e7-873d-91db89932c69.png)

this is 404.

does the list exist somewhere can can the readme be fixed up?

**Comment by Br3nda** [comment]
Is this where that link should go?
http://docs.ckan.org/en/latest/api/index.html#action-api-reference

**Comment by wardi** [comment]
Yes that's where it should go.
