### ISSUE TITLE
Problems installing ckanapi

### ISSUE THREAD

**Issue by Pilarbr82** [ckan/ckanapi#135]
Hi! im trying to install ckanapi, Any help would be really appreciate : Steps i follow

(activate)

`pip install ckanapi`

In development.ini

ckan.plugins=ckanapi

Restart..  then 

`paster serve /etc/ckan/default/development.ini`

I get this message:

File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 256, in _get_service
    raise PluginNotFoundException(plugin_name)
ckan.plugins.core.PluginNotFoundException: ckanapi

Thanks a lot

**Comment by wardi** [comment]
@Pilarbr82 ckanapi isn't a ckan extension/plugin, it's just a python library. You shouldn't need to add anything to your ckan settings to use it.

**Comment by Pilarbr82** [comment]
ok thank u,  newbie!

Sorry
