### ISSUE TITLE
Make new pypi release

### ISSUE THREAD

**Issue by mcarans** [ckan/ckanapi#140]
Following the fix by @wardi described in https://github.com/ckan/ckanapi/issues/139, please make an official release to pypi

**Comment by davidread** [comment]
I'm also wanting a new release, following #138 being merged.

And for some reason the version on master still says 4.1. The [commit](https://github.com/ckan/ckanapi/commit/673387329ab0db85024c5c37684179d9c4e9759c#diff-2eeaed663bd0d25b7e608891384b7298) doesn't seem to be merged or something

**Comment by wardi** [comment]
released 4.3
