### ISSUE TITLE
ckanapi - Python 3 support

### ISSUE THREAD

**Issue by amercader** [ckan/ckanapi#148]
Although tests pass on Python 3.6 my understanding from issues like #95 and #141 is that CLI usage is not yet supported (tests only cover usage as a library)

- [ ] Add tests that cover CLI usage
- [ ] Test Python 3.7 (and 3.8) on Travis
- [x] Replace usage of paster for the CLI by Click
- [ ] Fix linked issues and any other that is found
- [ ] Add py3 classifiers to setup.py (eg `Programming Language :: Python :: 3.7`) and ideally a description (from the README) so it comes up in PyPI.

**Comment by amercader** [comment]
@wardi can you review and see if I missed anything?

**Comment by zelima** [comment]
@amercader I can take on this

**Comment by wardi** [comment]
@amercader yes this looks good. The CLI does work in python 3 but not with the `-c` option since ckan itself can't be imported from python 3. Looking forward to having that restriction removed!

**Comment by amercader** [comment]
@zelima amazing thanks!

**Comment by simeonackermann** [comment]
With current CKAN 2.9.1 and Python 3 I can't execute ckanapi for local CKAN instances,resp get the error message:
```
File "/srv/app/src/ckan/ckanext/datastore/logic/auth.py", line 43, in <module>
    @p.toolkit.auth_allow_anonymous_access
  File "/srv/app/src/ckan/ckan/plugins/toolkit.py", line 563, in __getattr__
    raise AttributeError('`%s` not found in plugins toolkit' % name)
AttributeError: `auth_allow_anonymous_access` not found in plugins toolkit
```

**Comment by wardi** [comment]
ckanapi cli now supports local commands with Python 3 and CKAN 2.9+
