### ISSUE TITLE
Download resources

### ISSUE THREAD

**Issue by frafra** [ckan/ckanapi#150]
Even if downloading files is not part of the API, it would be nice to do that. Using `X-CKAN-API-Key` works just fine when requesting a private resource.

**Comment by MLaunch** [comment]
@mcarans - Did you figure this out? We're looking for the same information! Thanks!

**Comment by wardi** [comment]
Pass your api token as the apikey parameter and creating datapackages from the CLI (what the #194) fix was for should work.

Getting a correct URL for downloading private resources with `package_show`, `dump datasets` etc. should have always been working if you pass your api token as the apikey parameter.

**Comment by MLaunch** [comment]
Thanks so much @wardi!!
