### ISSUE TITLE
ContextualVersionConflict: (python-slugify 4.0.1 ... Requirement.parse('python-slugify<4,>=1.0'), {'ckanapi'})

### ISSUE THREAD

**Issue by mcarans** [ckan/ckanapi#163]
@wardi Following the release of the new CKAN version 4.4, I am getting this error (which I don't get with 4.3): 

ContextualVersionConflict: (python-slugify 4.0.1 ... Requirement.parse('python-slugify<4,>=1.0'), {'ckanapi'})

I don't see the upper bound in https://github.com/ckan/ckanapi/blob/master/setup.py (which has the wrong ckanapi version in it: version='4.3'), but when I look in the installed package I see the upper bound in lib/python3.8/site-packages/ckanapi-4.4.dist-info/METADATA:

```
Metadata-Version: 2.1
Name: ckanapi
Version: 4.4
Summary: A command line interface and Python module for accessing the CKAN Action API
Home-page: https://github.com/ckan/ckanapi
Author: Ian Ward
Author-email: ian@excess.org
License: MIT
Platform: UNKNOWN
Requires-Dist: setuptools
Requires-Dist: docopt
Requires-Dist: requests
Requires-Dist: python-slugify (<4,>=1.0)
Requires-Dist: six (<2.0,>=1.9)

UNKNOWN

```

**Comment by wardi** [comment]
@mcarans I just pushed out 4.5, the version requirement change was pulled in accidentally.
