### ISSUE TITLE
Web Scaping in Python for Large data set from CKANAPI

### ISSUE THREAD

**Issue by kumaranil02** [ckan/ckanapi#192]
I am trying to pull data from "https://opendata.nhsbsa.net/dataset/english-prescribing-dataset-epd-with-snomed-code/resource/374ee7ac-fd8e-4c3f-b7a9-6ea27cc16d63" website.

The website provides API to scrape large dataset. The data I am pulling is 17Million records.

API to pull the data :

'https://opendata.nhsbsa.net/api/3/action/datastore_search?offset=0&resource_id=EPD_SNOMED_202109&limit=5000'

Below is the code I am running.

```
import requests
import json

offset = 70000

for i in range(0,17000000,offset):
    url = 'https://opendata.nhsbsa.net/api/3/action/datastore_search?offset=' + str(i+1) + '&resource_id=EPD_SNOMED_'+ str(202109) +'&limit=' + str(offset)
    r= requests.get(url).json()
    df=pd.DataFrame(r['result']['records'])
    if i == 0:
      df.to_csv('data_pull.csv',mode='a', header=True,index=False)
    else:
      df.to_csv('data_pull.csv',mode='a', header=False,index=False)
```
The above code is taking more than 3hours and also gives duplicate values. There are no duplicates present in the actual data.

Please provide a better answer to below question:

https://stackoverflow.com/questions/70209859/web-scaping-in-python-for-large-data-set-from-api

suggestion needed on a better library or process to do this.

**Comment by wardi** [comment]
This is an issue tracker for the ckanapi client library and CLI tool, not support for scraping ckan sites with Python.

**Comment by kumaranil02** [comment]
Thank you for the quick response and clarification. Kindly advice if there is a better way to do this using ckanapi ? instead of ckan website scraping.

There resource id I am looking for is: **EPD_SNOMED_202109**

This has approx 17M records. I have read trough the ckanapi documents and tried few cli commands like 

`ckanapi action datastore_info id = 'EPD_SNOMED_202109'` to get hands on ckanapi.

Kindly suggest if possible.
