### ISSUE TITLE
how to download resources via search

### ISSUE THREAD

**Issue by aborruso** [ckan/ckanapi#197]
Hi,
in `ckanapi search datasets` there is not the `-D` option to download resources and output as datapackages.

I would like to use the cli to download all the resources of some dataset, not all (not via `dump datasets --all`).

Is there a way for a single dataset id? Is there a way via search?

Thank you

**Comment by wardi** [comment]
sure, you can `ckanapi dump datasets <id1> <id2> ...`  Search doesn't have the dowload option but that sounds like a useful feature if you're interested in working on it

**Comment by aborruso** [comment]
> sure, you can `ckanapi dump datasets <id1> <id2> ...` Search doesn't have the dowload option but that sounds like a useful feature if you're interested in working on it

I'm not able to write this code, but this could be a recipe for a recipes page, to download via search:

```bash
URL="https://mysample.url"
ckanapi -r "$URL" search datasets fq='(title:"taxes")' | \
jq -r '.id' | \
xargs -I _ ckanapi -r "$URL" dump datasets _ --datapackages=./out
```
