### ISSUE TITLE
Ckanapi hanging after load command

### ISSUE THREAD

**Issue by sparsons808** [ckan/ckanapi#202]
Each time I try to run ckanpapi load command ckanapi just hangs. Is there any support for this? does anyone know why this might be happening?

**Comment by wardi** [comment]
if you don't pass `-I` then ckanapi is waiting for input on stdin

**Comment by sparsons808** [comment]
So I do pass -I and some of the datasets load, but some don't, and the program is just left hanging until i abort it. thank you for your response.

**Comment by sparsons808** [comment]
so same thing happens even when I load data with curl
