### ISSUE TITLE
unit tests needed for datapackage export

### ISSUE THREAD

**Issue by wardi** [ckan/ckanapi#40]
@mattleduc do you have time to do this, or would you like me to add some unit tests?

**Comment by mattleduc** [comment]
I will have time to do this, but not until the first week of April.

**Comment by wardi** [comment]
@mattleduc first week of April is fine. Extending the stuff in https://github.com/ckan/ckanapi/blob/master/ckanapi/tests/test_cli_dump.py might be fine, unless you can think of a better way.

**Comment by mattleduc** [comment]
That's how I was planning on handling it, although mocking datasets might make things a bit more complicated.

**Comment by mattleduc** [comment]
Er, mocking resources.

**Comment by wardi** [comment]
I'd mock out the `dump_things()` `requests.get` loop by adding a `_download_resource_fn` parameter. Would be nice to move that heavily indented block into another function anyway.

**Comment by wardi** [comment]
fixed by #42
