### ISSUE TITLE
Allow to specify filenames according to requests lib format

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckanapi#45]
Allow to specify tuple `('filename.xls', open('filename.xls'))` for 'upload' or any other field.

Right now using `upload: open('filename.xls')` ckan won't receive the filename which will result in dummy 'upload' file, ie. http://localhost:5000/dataset/1b469259-02e2-43fa-864a-bf018eeef059/resource/799fb449-6249-4ea6-8ddd-24550b5b8dba/download/upload

**Comment by KrzysztofMadejski** [comment]
Note: if filename has UTF-8 chars then it's not correctly handled by ckan (ResourceUploader sees unicode string instead of cgi.FileStorage)

**Comment by wardi** [comment]
assuming we can close this, now
