### ISSUE TITLE
Unspecified dependencies

### ISSUE THREAD

**Issue by davidmegginson** [ckan/ckanapi#60]
Installing via pip on Python2, I ran into the following missing dependencies:

* formencode
* vdm
* sqlalchemy (and when installed, failed because the version was above 0.8)

I did not have any problems after a pip install in Python3.

**Comment by ostkrok** [comment]
I also ran into the same problem when installing ckanpi *after* installing ckan.
Installing just ckanapi in a fresh virtual environment seems to work just fine.

**Comment by wardi** [comment]
these are ckan dependencies. If ckanapi can import ckan (which it does for LocalCKAN) it assumes the ckan dependencies are installed correctly. Repeating those dependencies in ckanapi would be silly, it would very quickly go out of date and only work with some specific ckan version.

**Comment by davidmegginson** [comment]
So the question is why pip failed to install the dependencies in Python2, but not in Python3.
