### ISSUE TITLE
How to migrate users between CKANs using ckanapi CLI

### ISSUE THREAD

**Issue by florianm** [ckan/ckanapi#61]
I'm trying to migrate users between CKAN catalogues using the ckanapi CLI.

Is there a way to migrate users, seeing that `ckanapi dump users` does not dump their password hashes? Without those, naturally `ckanapi load users` will fail like this (usernames anonymised):
```
ckanapi dump users --all -r http://sourceckan -a my-sysadmin-api-key-source | ckanapi load users -r http://targetckan -a my-sysadmin-api-key-target
0 [1] --- None asdasdf
1 [2] 0.61s None asdfasdf
2 [3] 0.28s None asdfasdf
3 [4] 0.26s None asdfasdf
4 [5] 0.25s None asdfasdf
5 [6] 0.26s None asdasdf
6 [7] 0.25s None asdfasdf
7 [None] 0.33s None asdfasdf
1 [2] --- create ValidationError {"password":["Missing value"],"__type":"Validation Error"}
2 [3] 0.68s update ValidationError {"__type":"Validation Error","email":["Missing value"]}
3 [4] 0.73s create ValidationError {"password":["Missing value"],"__type":"Validation Error"}
4 [5] 0.68s create ValidationError {"password":["Missing value"],"__type":"Validation Error"}
5 [6] 0.67s create ValidationError {"password":["Missing value"],"__type":"Validation Error"}
6 [7] 0.71s create ValidationError {"password":["Missing value"],"__type":"Validation Error"}
7 [8] 0.70s create ValidationError {"password":["Missing value"],"__type":"Validation Error"}
8 [None] 0.68s create ValidationError {"password":["Missing value"],"__type":"Validation Error"}
```
This was run on a machine separate from the two (source and target) CKAN instances, using the respective sysadmin's API key.

**Comment by deniszgonjanin** [comment]
This is a CKAN limitation at the moment. Exporting the hashes is dependent on https://github.com/ckan/ckan/pull/2647

**Comment by florianm** [comment]
Got a working solution.

Note for datacats environments using ckanext-spatial:
* Create environment, let datacats initiate db as per normal
* datacats tweak --install-postgis
* do not db clean / db init

## Migrate users
* Dump the user table (data only, no schema) from the source CKAN
* Chown the sql file to yourself and an appropiate group (e.g. www-data)
* Delete the first three users from user.sql - the new CKAN will already have the "default" user.
```
sudo su
sudo -u postgres pg_dump -a -O -t user -f path/to/user.sql CKAN_DB_NAME
sudo chown florianm:www-data /mnt/projects/datacats/internal/user.sql
# delete lines "default", "logged_in", "visitor" from user.sql
```

## Restore users in target CKAN
* In this example, the target is a datacats CKAN environment.
* Datacats CKAN: print out the auto-generated passwords and copy the "postgres" one

```
cat ~/.datacats/ENV_NAME/sites/primary/passwords.ini
# prints passwords, copy postgres passwird
(datacats venv)me@machine:/path/to/ENV_NAME⟫ datacats shell
# datacats shell:
(ckan)shell@ENV_NAME:~$ psql -h db -d ckan -U postgres -f /path/to/user.sql
exit
```

## Backup groups, orgs, datasets
* Has to run after migrating users
* Source CKAN has to be online
```
ckanapi dump groups --all -p 3 -r http://internal-data.dpaw.wa.gov.au > path/to/groups.jsonl
ckanapi dump organizations --all -p 3 -r http://internal-data.dpaw.wa.gov.au > path/to/organizations.jsonl
ckanapi dump datasets --all -p 6 -r http://internal-data.dpaw.wa.gov.au > path/to/datasets.jsonl
```

## Load groups, orgs, datasets
* -I is capital i = load jsonl data
* Target CKAN has to be online
```
ckanapi load groups -p 3 -I path/to/groups.jsonl -r http://TARGET -a APIKEY
ckanapi load organizations -p 3 -I path/to/organizations.jsonl -r http://TARGET -a APIKEY
ckanapi load datasets -p 3 -I path/to/datasets.jsonl -r http://TARGET -a APIKEY
```
Where APIKEY is admin to TARGET CKAN.

## Migrate files, fix permissions
* This example migrates between two datacats CKANs. Other CKANs have to adjust their paths.
```
sudo rsync -Pavvr ~/.datacats/SOURCE/sites/primary/files/ ~/.datacats/TARGET/sites/primary/files/
sudo chown -R florianm:www-data ~/.datacats/TARGETites/primary/files/ 
```

## Download, install, enable extensions
As normal.
