### ISSUE TITLE
Harvest sources crash dump datasets

### ISSUE THREAD

**Issue by florianm** [ckan/ckanapi#68]
Tested environments:
* datacats CKAN, latest master (2.5.0a)
* source install CKAN, latest master (2.5.0a), upgraded since 2.3 master
* ckanext-harvest with a few harvest sources defined
* custom schema via ckanext-scheming (no "extra" fields allowed in dataset dict)

```
ckanapi dump datasets --all -p 6 -r http://SOURCE > datasets.jsonl
```
This will crash with a server error and broken pipe on the harvest sources, which are specialised datasets and collide with ckanext-scheming's well-defined, but rigid idea of dataset schemas.

Workarounds:
* delete harvest sources at source CKAN
* ckanapi dump chunks of datsets (with offset and max. parameters) omitting exactly only the harvest sources.

On a side note, some old datasets, which have been edited last before we switched to ckanext-scheming, still have "extra" fields, which will crash during `ckanapi load`. Had to manually remove the `extra` keys from those datasets to make ckanapi load them.

**Comment by wardi** [comment]
Hmm. if harvest sources are datasets dump datasets really *shouldn't* be crashing when trying to display them.  Can you provide the traceback?

**Comment by florianm** [comment]
Unfortunately not. We switched from using ckanext-harvest to using a custom python script, which was easier to adapt to the ever-changing harvest requirements.

Running on my instances now using ckanapi 3.6.dev0, all using a ckanext-scheming custom schema:

* CKAN 2.6.0a, no harvest sources configured: datasets, groups, orgs dump works ok
* CKAN 2.5.0a, no harvest sources configured: datasets, groups, orgs dump works ok
* CKAN 2.6.0a, one new harvest source configured:
  * no harvest run yet: dataset dump works ok
  * harvest source run once, 20 datasets harvested from same custom ckanext-scheming schema: harvest works ok

As I can't reproduce this any more, therefore closing this issue. With the caveat that harvest creates extra fields (with some config settings), and scheming frowns upon existing and populated extra fields, I'd say it's all good here.
