### ISSUE TITLE
Instructions for uploading a file are wrong

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckanapi#71]
The problem is that `url` is required on `resource_created`. I feel that's a problem with CKAN itself, so I created the issue https://github.com/ckan/ckan/issues/2769.

**Comment by wardi** [comment]
You're right. The docs here are aspirational.. one day they should work.

In the mean time we ought to fix the docs here. PR welcome!

**Comment by vitorbaptista** [comment]
Sent PR at https://github.com/ckan/ckanapi/pull/74

**Comment by wardi** [comment]
this has been fixed in ckan master (url no longer required)

**Comment by wardi** [comment]
added to the readme as well https://github.com/ckan/ckanapi/commit/bdc543180a908f55e826d6daeebdd290fab3decc
