### ISSUE TITLE
syncing.SynchronizationClient is obscure

### ISSUE THREAD

**Issue by xapple** [ckan/ckanapi#84]
It seems like something really useful, to automatically sync datasets to a CKAN instance, but I can't figure out how it works. The documentation is very vague. It says:

> data – Data to be synchronized. Should be a dict (or dict-like) with top level keys coresponding to the object type, mapping to dictionaries of {'id':  object}.

But so what is `<object>` supposed to be like ? What dictionary should I call that method with ? An example usage would really be welcome.

**Comment by wardi** [comment]
I don't know what a syncing.SynchronizationClient is. Are you on the right repo?

**Comment by xapple** [comment]
Sorry it was the wrong repo indeed. There is https://github.com/opendatatrentino/ckan-api-client which has almost the same name and almost the same functionality. Wanted to use that one because synchronization is a much better approach that upload/delete for this problem. It's like rsync against cp and rm.
