### ISSUE TITLE
Authentication and api keys

### ISSUE THREAD

**Issue by xapple** [ckan/ckanapi#85]
So how do you pass your authentication key with ckanapi ? It seems like you just need to add it to the header as it specifies here: http://docs.ckan.org/en/latest/api/index.html#authentication-and-api-keys

**Comment by wardi** [comment]
use the RemoteCKAN apikey parameter, as show in the readme, e.g. https://github.com/ckan/ckanapi#file-uploads

**Comment by xapple** [comment]
I did a search for the word "authentication" on the readme but it returned no results. Maybe you should make a proper documentation and put it on read the docs ?

**Comment by wardi** [comment]
@xapple for sure, some complete docs would be great. It's on my list of things I hope to find time for. As always, contributions are welcome!

**Comment by xapple** [comment]
OK cool, thanks for your answer ! Very useful little API ! I'll tell you if I find anything else.
